name: Elixir CI

on:
  pull_request:
  push:
    branches:
      - master
      - 'v*'

jobs:
  mix_test_old:
    name: mix test (Elixir ${{matrix.elixir}} | OTP ${{matrix.otp}})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.11.x
            otp: 24
            os: ubuntu-24.04
          - elixir: 1.12.x
            otp: 24
            os: ubuntu-24.04
          - elixir: 1.13.x
            otp: 25
            os: ubuntu-24.04
          - elixir: 1.14.x
            otp: 25
            os: ubuntu-24.04
          - elixir: 1.15.x
            otp: 26
            os: ubuntu-24.04
          - elixir: 1.16.x
            otp: 26
            os: ubuntu-24.04
          - elixir: 1.17.x
            otp: 27
            os: ubuntu-24.04
          - elixir: 1.18.x
            otp: 27
            os: ubuntu-24.04
          - elixir: 1.19.x
            otp: 28
            os: ubuntu-24.04
            warnings_as_errors: true
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.hex
            ~/.mix
            _build
          key: ${{ matrix.otp }}-${{ matrix.elixir }}-build
      - run: mix compile --warnings-as-errors
        if: matrix.warnings_as_errors
      - run: mix test
  dialyzer:
    name: mix dialyzer
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.19.x
            otp: 28
    env:
      MIX_ENV: test
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - name: Install Dependencies
        run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get --only test
      - name: Cache build artifacts
        uses: actions/cache@v3
        with:
          path: |
            ~/.hex
            ~/.mix
            _build
          key: ${{ matrix.otp }}-${{ matrix.elixir }}-dialyzer
      - run: mix dialyzer --halt-exit-status
